language: go

go:
 - "1.11.x"

sudo: required
dist: trusty

install:
  - go get -t ./...
  - go get golang.org/x/lint/golint
  # Install gometalinter
  - go get github.com/alecthomas/gometalinter

script:
 - go test -race -v .
 - gometalinter --install
 - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign --tests .
